---
title: "Syllabus"
subtitle: "Stat 20: Introduction to Probability and Statistics"
toc: true
doi: "Fall 2022"
doi-title: Term
author:
    - Andrew Bray
    - Iain Carmichael
    - Jeremy Sanchez
    - Shobhana Murali Stoyanov
author-title: Instructors
abstract: "[Welcome to the Age of Data]{style=\"font-family: Cinzel, serif; font-size: 1.2em\"}, where claims made using data are all around us: in the news, in the pages of scientific journals, in the policies of government, and in the board rooms of companies across the world. In this course you will explore the forms of claims that are made using data. Some of these are subtle claims about the structure of the data at hand. Others are grand claims about scientific truths or predictions of what will happen in the future. This course will train your ability to critique and construct such arguments made using data."
abstract-title: ""
theme: [sandstone, assets/styles.scss]
toc-depth: 4
---

### Course Culture

Students taking Stat 20 come from a wide range of backgrounds. We hope to foster an inclusive and supportive learning environment based on curiosity rather than competition. All members of the course community—the instructor, students, tutors, and readers—are expected to treat each other with courtesy and respect. 

You will be interacting with course staff and fellow students in several different environments: in class, in plenary, over the discussion forum, and in office hours. Some of these will be in person, some of them will be online, but the same expectations hold: be kind, be respectful, be professional.

If you are concerned about classroom environment issues created by other students or course staff, please come talk to us about it.

### Mode of Instruction

This course is structured as a flipped class, meaning that you'll first be encountering new concepts in statistics and data science *outside* of class. Class time is dedicated expanding on the work you've done outside of class by working through questions solo, in groups, and as a class. 

The reason that this course is structured in this manner is that applied data science is a complex field that unites scientific thinking, computing, mathematics, and an understanding of the context of the data. We will be able to tackle more interesting and challenging questions if we make room during class time to work on them while we're all in the same place.

#### Before class

**It is your responsibility to become familiar with the topics that appear in the course notes and to work through the reading questions by 11 pm on the night before Wednesday's and Friday's class sessions**. You're encouraged to experiment to find the method that works best for you: downloading the notes as a pdf and making notes on them, asking and answering questions over the class forum, reading through the website and discussing with friends, etc.

#### During class on Wednesday and Friday

Class time (2 hrs) will be spent on a range of activities, but the most common will be concept questions (using Poll Everywhere) and working through data analysis questions in groups. Most of the data analysis questions will be taken from the lab assignments, so the most efficient way to complete your labs will be an active participant in class. Attendance is expected on Wednesday and Friday.

#### During class on Monday

Monday is a shorter (1 hr) and less-structured class dedicated to finishing up work on your assignments, which are due Monday night.

#### Plenary lectures

While in general this course does not have full lectures, there are a few select exceptions. Several times during the semester, the course will be hosting a special guest to give a lecture to all 8 sections of Stat 20. These speakers will all be preeminent scientists and data scientists working in academia and industry and will speak on how the ideas and tools and the we discuss in class look in the real world!

Each plenary lecture will be announced once it has been confirmed. We will send out an RSVP form for you to indicate whether you expect to attend or not. Please fill this out so that we have a good measure of the amount of students we can expect. Those students who do show up will be able to complete an accompanying extra credit assignment on Gradescope worth 0.5 percentage points.

#### Office Hours

Tutors and the instructor will offer office hours each week across a range of times. We ask that you visit the office hours of the instructor of your lab section but you're welcome to visit the office hours of any tutor: not only the one who works in your section. We may adjust the office hour schedule throughout the semester as we understand student needs and preferences.

Please come to office hours! Coming to office hours does not send a signal that you are behind or need extra help. On the contrary, coming to office hours early and often tends to co-occur with success in the course.

Feel free to come to office hours even if you don’t have a specific question about an assignment. The course staff is happy to chat about the course material, statistics in general, careers in statistics, or whatever other statistics or data science topics are on your mind!

#### COVID policy

Maintaining your health and that of the Berkeley community is of primary importance to course staff, so if you are feeling ill or have been exposed to illness, please do not come to class. All of the materials used in class will be posted to the course website. You're encouraged to reach out to fellow students to discuss the class materials or stop by office hours to chat with a tutor or the instructor.

### Materials

#### Textbook

The primary materials for the course are the lecture notes, which will be posted to the course website in advance of class. The following textbooks are valuable supplementary texts and will be drawn upon for additional readings:

- [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) by &#199;etinkaya-Rundel and Hardin (freely available online)
- [Statistics](https://wwnorton.com/books/9780393929720), Freedman, Pisani, and Purves
- [Data Visualization: A Practical Introduction](https://socviz.co/), Healy (freely available online)
- [Hands-on Programming with R](https://rstudio-education.github.io/hopr/), Grolemund (freely available online)
- [R for Data Science](https://r4ds.had.co.nz/), Wickham and Grolemund (freely available online)

#### RStudio

The software that we'll be using for our data analysis is the free and open-source language called R that we'll be interacting with via software called RStudio. As a Berkeley student, you have your own version of RStudio waiting you for at: [http://stat20.datahub.berkeley.edu](http://stat20.datahub.berkeley.edu). Most students taking Stat 20 have no experience programming; we'll teach you everything you need to know!

### Course communication

#### Discussion forum

Out-of-class communication for this course will be held on [Ed](https://edstem.org). Keep an eye out for an e-mail invite in the first week of classes. We have this forum so you can ask and answer questions with your fellow students and course staff! It’s really useful for staying up-to-date with the course and learning from your classmates. 

If you would like to communicate with us regarding a personal matter, you can do that in Ed by flagging your post as private, or you can e-mail! Your instructor will indicate their preference for you, or if they don't, you can ask your instructor for what they prefer.

#### Course website

All of the assignments will be posted to the course website at [https://stat20.org](https://stat20.org). This also holds the course notes, the syllabus, and links to Gradescope, Ed, and RStudio.

### Assignments, Exams, and Grading

#### Turning-in assignments

You will be turning in your assignments on a platform called  [Gradescope](https://www.gradescope.com/). This is also the platform where your assignments will be graded, so you can return there to get feedback on your work. You are also welcome to file a regrade request if you notice that we made an error in applying the rubric to your work, but please do so within a week of the grades being posted.

#### Labs 

Labs are long-form assignments designed to apply the concepts from the lecture notes in the cause of doing an analysis of real data. This will involve both writing code and communicating your thoughts and findings in English. We'll be working through the most challenging problems from the labs in class, but you may have to complete them on your own outside of class time. Most will be written-up and submitted individually but some will be group submissions.

There will be a lab every week or two that will be due at the standard assignment deadline of 11 pm on Monday night, on Gradescope.

Because the labs take a while to grade, we will be giving completion grade credit to the majority of problems and assessing a select few questions (decided after the due date) for credit.

We (instructors) do recognize there are things going on in each of your lives which you might need to handle throughout the course. Because of this, when it comes to labs, we’re going to give you **one, two-day extension** (until Wednesday at 11p), no questions asked. To use the extension, we ask that you notify us, by private Ed post or through e-mail of your decision *before* the standard due date of Monday at 11pm.

##### Submission Format 

Labs are to be submitted as PDF files rendered from Quarto Documents (.qmd). Don't worry if you're not familiar with the Quarto Document as we will teach you about it! The PDF-from-QMD format is both attractive and readable when it comes to grading. 

We also ask that you make sure to assign your page(s) to each lab questions when prompted by Gradescope to do so before you confirm your submission. This allows graders to work quicker and therefore get your papers back to you quicker. 

Starting with Lab 2 and for the rest of the semester, we will exact a *10 percent penalty* on any labs which fail to meet these formatting requirements. This penalty will apply *on top* of the standard late penalty which will be described below in the **Late Work** section of this syllabus.


#### Problem Sets

The problem set is meant as practice: practice with the concepts and methods from the lecture notes that you'll need to hone in order to do the labs well and succeed on the quizzes. The problems will be selected from handouts that we will work on in class, so if you work on the in-class handouts, you will in essence be completing part of your problem set. The run more like traditional homework assignments that drill the concepts you've learned in the reading notes rather than ask you to apply what you've learned in a new setting (such as in the labs).

Since the goal of these is just practice, they will be graded credit / no credit, where credit is an earnest attempt (evidence that you worked on most of the problems). They will also be due at the standard assignment deadline of 11 pm on Monday night.

Problem sets will be released weekly or biweekly. To make sure that the problem sets also serve as study material, *we will be providing video solutions to them.* The videos will be recorded by the instructional staff and will be released *Tuesday morning at 8am (the morning after the deadline).*

You will be given one problem set drop during the semester, meaning that the lowest problem set score you attain will be dropped. Note these assignments are completion grade anyway, so this essentially means you can skip one problem set if you'd like.

##### Submission Format

Since the problem sets are completion grade, we do not require any submission format other than one which is easily readable, though we strongly prefer PDF files rendered from Quarto Documents (.qmd).

#### Reading Questions

Reading questions serve to check your understanding and engagement while going through the lecture notes prior to class. There will be a handful of questions per “lecture” and they can be a mix of multiple choice, short answer, and coding questions. You will answer them directly on Gradescope. Note that the reading questions will be due 11 pm the night before class: that is, on 11 pm Tuesdays for the Wednesday lecture, and 11 pm Thursdays for the Friday lecture.


#### Quizzes

Quizzes will be held biweekly on Thursday nights/Fridays.

Quizzes reinforce the most important concepts from the lecture notes and provide your the opportunity to work through misunderstandings with peers and the instructor. 

Each quiz has two components: an *individual* component to be completed the night before class (Thursday night), and a *group* component to be completed in class with a group ranging from 2 to 4 students. 

The *individual* component will take the place of the Thursday night reading on the week of the quiz. It will be released at 6pm and will be due at 11pm on Gradescope. It has a 25 minute time limit.

The *group* component will take place during the first 15 minutes of class on Friday. It will be due on Gradescope as a group submission, meaning that only one member of your group need submit. Once the submission has gone through, you can add your group members on the following page. Make sure to add them by e-mail if it allows, since there may be multiple students with the same first and last name enrolled in the course! 


Your final (composite) quiz grade will be the **average** of your group and individual quiz scores. Should you not be able to attend class to take the group quiz due to extenuating circumstances (illness, family emergency, etc.), you may fill out a form that we will send out to you via e-amil prior to Friday. 

You will be given *one* overall quiz drop, meaning that the lowest composite score you attain on a quiz will be dropped.

#### Exam

The final exam will be held in person during finals week. The Stat 20 Final is scheduled to be held in Group 11: Wednesday 12/14/22 from 3-6pm.

#### Grading

Your final grade in the course will be computed based on:

- Labs: 60%
- Reading Questions: 5%
- Quizzes 10%
- Problem sets 5%
- Final 20%

Within each category, each assignment is equally weighted. For example, within the Labs category, each Lab has equal weight. 

The goal of your course staff is to help you develop and demonstrate your mastery of the material. As such, the course will not be curved and standard cutoffs will be used to determiner letter grades (> 90% is some kind of A, etc.). 

### Policies

#### Accomodations for students with disabilities

Stat 20 is a course that is designed to allow all students to succeed. If you have letters of accommodations from the Disabled Students’ Program, please share them with your instructor as soon as possible, and we will work out the necessary arrangements.

#### Late Work

This message applies in cases where a drop or extension has not been or has already been used.

Unfortunately, with a class of this size, we are unable to keep track of and grade submissions of labs, reading question, and problem sets that come in very late. If you narrowly miss the 11 pm deadline, you will still be able to submit until midnight with a small grade penalty (10% reduction in score). If you're still not done with your lab by midnight, you can submit until noon on Tuesday with a larger penalty (30% reduction).


### Collaboration policy

You are encouraged to collaborate with your fellow students on problem sets and labs, but the work you turn in should reflect your own understanding and all of your collaborators must be cited. Quizzes, exams must reflect only your work.

Researchers don't use one another's research without permission; scholars and students always use proper citations in papers; professors may not circulate or publish student papers without the writer's permission; and students may not circulate or post non-public materials (quizzes, exams, rubrics-any private class materials) from their class without the written permission of the instructor.

The general rule: you must not submit assignments that reflect the work of others unless they are a cited collaborator.

The following examples of collaboration **are** allowed and in fact encouraged!

- Discussing how to solve a problem with a classmate.
- Showing your code to a classmate along with an error message or confusing output.
- Posting snippets of your code to the discussion forum when seeking help.
- Helping other students solve questions on the discussion with conceptual pointers or snippets of code that doesn't whole hog give away the answer.
- Googling the text of an error message.
- Copying small snippets of code from answers on Stack Overflow.

The following examples are **not** allowed:

- Leaving a representation of your assignment (the text, a screenshot) where students (current and future) can access it. Examples of this include websites like course hero, on a group text chain, over discord/slack, or in a file passed on to future students.
- Accessing and submitting solutions to assignments from other students distributed as above.
- Googling for complete problem solutions.
- Working on the reading questions or individual quizzes in collaboration with other people or resources. These assignments must reflect individual work.
- Submitting work on an exam that reflects consultation with outside resources or other people. Exams must reflect individual work.

If you have questions about the boundaries of the policy, please ask. There is never a penalty for asking! We’re always happy to clarify.

#### Please Don’t Cheat

We’re sorry this section of the syllabus is so sad. We don’t like it either. But it’s upsetting to students if other students are cheating, so we use TurnItIn to detect cheating on labs and have access to data through Gradescope to detect cheating on quizzes.

Students determined to have violated the academic misconduct policy by the Center for Student Conduct will receive a grade penalty in the course and a sanction from the university which is generally: (i) First violation: Non-Reportable Warning and educational intervention, (ii) Second violation: Suspension/Disciplinary Probation and educational interventions, (iii) Third violation: Dismissal.

And again, if you have questions about the boundaries of the collaboration policy, please ask!


### Frequently Asked Questions

1. What should I do if I'm on the waitlist?

   Attend lecture and section (remember, we are teaching it as *one* two hour class), and submit all assignments on time. After 3 class meetings, we will take a look at the waitlist.

2. Are class sessions recorded?

   No. Class sessions feature a mix of group problem solving, activities, and discussion and don't lend themselves to recording. The course notes are the main reference source for the course. Any materials used during the class session will be posted to the course website.

3. Is attendance required?
   
   No, but it is difficult to succeed in this course if you are not regularly attending class. Class sessions are designed to be an effective and efficient format to make progress on important assignments. Plus, it's a great way to meet your fellow students and learn from one another!
   
4. What if I join the class late?

   If you join the class within the first two weeks, read this course syllabus very carefully, read the lecture notes, take a look at gradescope to get a sense of any assignments that may have already passed, and visit office hours to check that you're up to date with things. The first two weeks of material are very important so you will be able to make up assignments.
   
   After two weeks into the semester, you'll have too much material that you'll need to make up, so you will have to wait to a subsequent semester to take Stat 20.
   
5. Why is the final exam date listed here different than the one I see in CalCentral?

   CalCentral automatically shows the default exam date associated with your lecture time. Stat 20 was approved to have a single exam time for all 8 lectures. Therefore the date and time listed here in the syllabus is correct; you can ignore what you see in CalCentral.
   
6. What if I have a final for another course at the same time as the Stat 20 final?

   That won't be a problem. We will organize another exam slot for those students with exam conflicts. We'll announce more information about this in November.
