---
title: "Lab 1: Getting Started"
---

[[Discuss]{.btn .btn-primary}](https://app.perusall.com)

This first lab has only one question:

> Where are you from *or* where would you like to visit?

Please submit a one page pdf, generated from a .qmd file in RStudio, that answers that question. Title the file `lab-1.qmd`. Your answer should contain the following components:

-  The county and state that you are from. If you are from abroad, provide the name of a county and state that you would like to visit. This should show up as a *header* (larger, heavier font).

-  1-3 paragraphs about this county in text, as described by Wikipedia.

-  Include a hand drawn sketch of your favorite place. Tinker with the image options to size and align it to your liking[^1].

-  A numbered list of your top three favorite things about this county.

-  A sentence at the bottom with an acknowledgement that text came from Wikipedia. Also include a link to the Wikipedia page.

The pdf that you submit to Gradescope should be titled `lab-1.pdf`.

[^1]: To upload your sketch, a photo of it, transfer the photo to your laptop, upload it to RStudio, then navigate to it after clicking "Browse" in the "Insert image" screen.
